---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install httpd package
    yum:
      name: httpd
      state: latest  
    when: ansible_distribution == "RedHat"

  - name: isntall php package
    yum:
      name: php
      state: latest
    when: ansible_distribution == "RedHat"

