---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: remove httpd package
    yum:
      name: httpd
      state: absent  

#  - name: add php support for apache
#   yum:
#     name: libapache2-mod-php
